### ISSUE TITLE
New firmware released

### ISSUE THREAD

**Issue by bogdan799** [systemik/Kobra3-Firmware#1]
Hey, first of all I want to thank you for all the work you have done, it's amazing!!

There's a new version of firmware released yesterday, and from what I can tell there's something going on for LAN:

<img width="340" alt="image" src="https://github.com/user-attachments/assets/f5989c19-8281-4d83-ab8c-89b5536f9d2a">
<img width="240" alt="image" src="https://github.com/user-attachments/assets/cb71c222-ae61-4573-9a21-1a2923a4d618">

Can you please add url to the new firmware as you did for the two previous ones so that I can research it a bit?

Thank you!

**Comment by systemik** [comment]
Here it is:

**Comment by bogdan799** [comment]
thank you

well, this might be interesting:

<img width="627" alt="image" src="https://github.com/user-attachments/assets/9ce9157a-01bc-41e2-b464-5a2d5d523640">
