### ISSUE TITLE
Not the correct folder?

### ISSUE THREAD

**Issue by cr4sh0v3r** [systemik/Kobra3-Firmware#17]
The update function is enabled when the file update.swu is into the update folder e not into aGVscF9zb3Nf, but the printer not starts updating, something wrong into the folder structure?

**Comment by systemik** [comment]
It depends which firmware the printer run. Latest version use the strange name and starts either at boot or when you insert the key. Previous version was using the update folder and update is launched via the screen menu.

**Comment by cr4sh0v3r** [comment]
2.3.3.9_11.6. Tried several times, i've always the update firmware error and doesn't start

**Comment by systemik** [comment]
I'll retest everything and repackage the firmware by Wednesday end of day. I'll answer back here when done.

**Comment by cr4sh0v3r** [comment]
ok done, it was zip not correctly working, used the same folder structure now is loaded
